apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: fkrk56/apcauth
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://kjw:1234@mongo-mongodb.default.svc.cluster.local:27017/auth"
            - name: BROKER_URI
              value: "my-cluster-kafka-external-bootstrap:9094"
