apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  namespace: my-kafka-project
  name: my-cluster
spec:
  kafka:
    replicas: 1
    listeners:
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        type: nodeport
        port: 9093
        tls: false
        configuration:
          bootstrap:
            nodePort: 32100
          brokers:
          - broker: 0
            nodePort: 32000
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: nks-block-storage
        size: 1Gi
        deleteClaim: false
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      class: nks-block-storage
      size: 1Gi
      deleteClaim: false
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
  entityOperator:
    topicOperator: {}
    userOperator: {}