apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: fkrk56/apcproduct
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              value: "mongodb://kjw:1234@mongo-mongodb.default.svc.cluster.local:27017/auth"
